# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-12 04:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vehicles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_id', models.DecimalField(decimal_places=7, max_digits=7)),
                ('vehicle_man', models.CharField(max_length=30)),
                ('year', models.DecimalField(decimal_places=4, max_digits=4)),
                ('active', models.DecimalField(decimal_places=2, max_digits=2)),
                ('dealer_id', models.DecimalField(decimal_places=7, max_digits=7)),
            ],
        ),
    ]
