# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-12 05:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicles',
            name='active',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='dealer_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='vehicle_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='year',
            field=models.IntegerField(),
        ),
    ]
