# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-12 05:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0002_auto_20171212_0538'),
    ]

    operations = [
        migrations.CreateModel(
            name='autos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_id', models.IntegerField()),
                ('auto_man', models.CharField(max_length=30)),
                ('year', models.IntegerField()),
                ('active', models.IntegerField()),
                ('dealer_id', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='vehicles',
        ),
    ]
